### ISSUE TITLE
插件搜索字段不匹配最新版本owl-admin

### ISSUE THREAD

**Issue by krvipsoft** [Slowlyo/owl-menu-search#1]
$menus = Admin::adminMenuModel()::query()->where('visible', 1)->orderBy('order')->get()->toArray();

正确的为$menus = Admin::adminMenuModel()::query()->where('visible', 1)->orderBy('custom_order')->get()->toArray();

**Comment by slowlyo** [comment]
可以提个pr 🤣

**Comment by slowlyo** [comment]
已修复
